name: flutter_app_upgrade_plus
description: App 升级功能
version: 1.0.0
homepage: https://github.com/cpyczd/flutter_app_upgrade_plus

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # plugin:
  #   androidPackage: com.flutter.flutter_app_upgrade
  #   pluginClass: FlutterAppUpgradePlugin
  plugin:
    platforms:
      android:
        package: com.flutter.flutter_app_upgrade
        pluginClass: FlutterAppUpgradePlugin
      ios:
        pluginClass: FlutterAppUpgradePlusPlugin

  
